export const EXTENDED_LAYOUT_OPTIONS = [
  { group: 'Grid (Classic)', options: [
    { value: 'grid', label: 'Standard Auto Grid' },
    { value: 'grid_1col', label: '1-col Grid (Full Width)' },
    { value: 'grid_2col', label: '2-col Grid (Half Width)' },
    { value: 'grid_3col', label: '3-col Grid' },
    { value: 'grid_4col', label: '4-col Grid' },
    { value: 'grid_5col', label: 'Standard 5-col Grid' },
    { value: 'grid_6col', label: '6-col Grid (Compact)' },
    { value: 'grid_7col', label: '7-col Grid' },
    { value: 'grid_8col', label: '8-col Grid (Dense)' },
    { value: 'grid_9col', label: '9-col Grid' },
    { value: 'grid_10col', label: '10-col Grid (Micro)' },
    { value: 'grid_classic', label: 'Spotify Classic Grid' },
    { value: 'grid_apple', label: 'Apple Music Album Grid' },
    { value: 'grid_compact', label: 'Compact Grid (Dense)' },
    { value: 'grid_relaxed', label: 'Relaxed Grid (Airy)' },
    { value: 'grid_large', label: 'Large Cover Grid' },
    { value: 'grid_small', label: 'Small Cover Grid' },
    { value: 'grid_rounded', label: 'Rounded Edge Grid' },
    { value: 'grid_square', label: 'Sharp Square Grid' },
    { value: 'grid_portrait', label: 'Portrait Cover Grid' },
    { value: 'grid_landscape', label: 'Landscape Cover Grid' },
    { value: 'grid_offset', label: 'Offset Staggered Grid' },
    { value: 'grid_circular', label: 'Circular Avatar Grid' },
  ]},
  { group: 'Carousel (Horizontal Scroll)', options: [
    { value: 'carousel', label: 'Standard Carousel' },
    { value: 'carousel_endless', label: 'Endless Loop Carousel' },
    { value: 'carousel_coverflow', label: 'Cover Flow 3D' },
    { value: 'carousel_snapping', label: 'Snap-to-Center Carousel' },
    { value: 'carousel_freoscroll', label: 'Free Scroll Carousel' },
    { value: 'carousel_peeking', label: 'Peeking Edges Carousel' },
    { value: 'carousel_fade', label: 'Edge Fade Carousel' },
    { value: 'carousel_zoom', label: 'Center Zoom Carousel' },
    { value: 'carousel_stacked', label: 'Stacked Cards Carousel' },
    { value: 'carousel_parallax', label: 'Parallax Background Carousel' },
    { value: 'carousel_perspective', label: 'Perspective Tilt Carousel' },
    { value: 'carousel_ticker', label: 'Auto-Scrolling Ticker' },
    { value: 'carousel_dual', label: 'Dual Row Carousel' },
    { value: 'carousel_hero', label: 'Hero Sized Carousel' },
  ]},
  { group: 'List (Vertical)', options: [
    { value: 'list', label: 'Numbered Song List' },
    { value: 'list_compact', label: 'Compact Density List' },
    { value: 'list_detailed', label: 'Detailed Info List' },
    { value: 'list_ranking', label: 'Top 100 Ranking List' },
    { value: 'list_minimal', label: 'Text-Only Minimal List' },
    { value: 'list_cards', label: 'Card-based List Items' },
    { value: 'list_alternating', label: 'Alternating Row Colors List' },
    { value: 'list_separated', label: 'Divided Separator List' },
    { value: 'list_floating', label: 'Floating Row List' },
    { value: 'list_expanded', label: 'Expanded Height List' },
    { value: 'list_stats', label: 'Analytics Stats List' },
    { value: 'list_lyrics', label: 'Lyrics Focus List' },
    { value: 'list_credits', label: 'Credits & Contributors List' },
    { value: 'list_billboard', label: 'Billboard Chart List' },
  ]},
  { group: 'Minimal (Compact Tiles)', options: [
    { value: 'minimal', label: 'Standard Minimal Tiles' },
    { value: 'minimal_quick_access', label: 'Quick Access Tiles (2-col)' },
    { value: 'minimal_micro', label: 'Micro Pill Tiles' },
    { value: 'minimal_text', label: 'Text-Heavy Minimal' },
    { value: 'minimal_icon', label: 'Icon-Focused Minimal' },
    { value: 'minimal_borderless', label: 'Borderless Minimal' },
    { value: 'minimal_outlined', label: 'Outlined Minimal Tiles' },
    { value: 'minimal_floating', label: 'Floating Shadow Minimal' },
    { value: 'minimal_neumorphic', label: 'Neumorphic Tiles' },
    { value: 'minimal_monochrome', label: 'Monochrome Minimal' },
    { value: 'minimal_vibrant', label: 'Vibrant Accent Minimal' },
  ]},
  { group: 'Hero (Full-Width)', options: [
    { value: 'hero', label: 'Standard Full-Width Hero' },
    { value: 'hero_cinematic', label: 'Cinematic Widescreen Hero' },
    { value: 'hero_split', label: 'Split Screen Hero' },
    { value: 'hero_overlay', label: 'Text Overlay Hero' },
    { value: 'hero_gradient', label: 'Gradient Blend Hero' },
    { value: 'hero_video', label: 'Video Background Hero' },
    { value: 'hero_parallax', label: 'Parallax Scroll Hero' },
    { value: 'hero_interactive', label: 'Interactive Mouse Hero' },
    { value: 'hero_carousel', label: 'Rotating Hero Carousel' },
    { value: 'hero_countdown', label: 'Release Countdown Hero' },
  ]},
  { group: 'Bento Grid', options: [
    { value: 'bento', label: 'Standard Bento Grid' },
    { value: 'bento_asymmetric', label: 'Asymmetric Bento' },
    { value: 'bento_symmetrical', label: 'Perfect Square Bento' },
    { value: 'bento_focus', label: 'Center Focus Bento' },
    { value: 'bento_scattered', label: 'Scattered Layout Bento' },
    { value: 'bento_modular', label: 'Modular Blocks Bento' },
    { value: 'bento_fluid', label: 'Fluid Responsive Bento' },
    { value: 'bento_mosaic', label: 'Mosaic Tile Bento' },
    { value: 'bento_hero', label: 'Hero Integrated Bento' },
    { value: 'bento_dynamic', label: 'Dynamic Sizing Bento' },
  ]},
  { group: 'Masonry Grid', options: [
    { value: 'masonry', label: 'Standard Masonry' },
    { value: 'masonry_pinterest', label: 'Pinterest Style Masonry' },
    { value: 'masonry_waterfall', label: 'Waterfall Layout' },
    { value: 'masonry_tight', label: 'Tight Gaps Masonry' },
    { value: 'masonry_loose', label: 'Loose Gaps Masonry' },
    { value: 'masonry_columns_3', label: '3-Column Fixed Masonry' },
    { value: 'masonry_columns_4', label: '4-Column Fixed Masonry' },
    { value: 'masonry_staggered', label: 'Staggered Entry Masonry' },
    { value: 'masonry_organic', label: 'Organic Flow Masonry' },
    { value: 'masonry_mixed', label: 'Mixed Content Masonry' },
  ]},
  { group: 'Story / Vertical', options: [
    { value: 'story', label: 'Instagram Style Stories' },
    { value: 'story_tiktok', label: 'TikTok Vertical Scroll' },
    { value: 'story_youtube', label: 'YouTube Shorts Format' },
    { value: 'story_snap', label: 'Snapchat Spotlight Style' },
    { value: 'story_fullscreen', label: 'Fullscreen Vertical' },
    { value: 'story_cards', label: 'Vertical Swiping Cards' },
    { value: 'story_paged', label: 'Paged Vertical Scroll' },
    { value: 'story_immersive', label: 'Immersive Video Story' },
  ]},
  { group: 'Magazine Editorial', options: [
    { value: 'magazine', label: 'Standard Editorial' },
    { value: 'magazine_news', label: 'News Portal Format' },
    { value: 'magazine_interview', label: 'Artist Interview Layout' },
    { value: 'magazine_review', label: 'Album Review Layout' },
    { value: 'magazine_feature', label: 'Feature Article Style' },
    { value: 'magazine_grid', label: 'Editorial Photo Grid' },
    { value: 'magazine_typographic', label: 'Heavy Typography Layout' },
    { value: 'magazine_minimal', label: 'Minimalist Editorial' },
    { value: 'magazine_retro', label: 'Retro Zine Style' },
  ]},
  { group: 'Music Timeline', options: [
    { value: 'timeline', label: 'Standard Chronological' },
    { value: 'timeline_release', label: 'Release History Timeline' },
    { value: 'timeline_era', label: 'Artist Eras Timeline' },
    { value: 'timeline_vertical', label: 'Vertical Path Timeline' },
    { value: 'timeline_horizontal', label: 'Horizontal Scroll Timeline' },
    { value: 'timeline_interactive', label: 'Interactive Drag Timeline' },
    { value: 'timeline_milestone', label: 'Career Milestone Timeline' },
    { value: 'timeline_compact', label: 'Compact History Timeline' },
  ]},
  { group: 'Search Page Layouts', options: [
    { value: 'genre_tiles', label: 'Genre Tiles (Start Browsing)' },
    { value: 'ad_break_banner', label: 'Advertisement Banner' },
    { value: 'hashtag_slides', label: 'Hashtag Slides (Discover Something New)' }
  ]}
];
